application:
  library-path: 'C:\neurotec\neurotec\neurotec\Bin\Win64_x64'
  server-url: http://localhost
  quality: 61
spring:
  application:
    admin:
      enable: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/bauchidb
    hibernate:
      ddl-auto: none
      event.merge.entry_copy_observer: allow
    hikari:
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.jdbc.lob.non_contextual_creation: true
lamis:
  temp-dir: runtime/
  module-path: modules
lamisplus:
  neurotec:
    plugin-search-path: 'C:\neurotec\neurotec\neurotec\Bin\Win64_x64'
    identification-threshold: 60
    license-server: /local
    license-port: 5000
    license-components:
      - Biometrics.FingerExtraction
      - Biometrics.Standards.FingerTemplates
      - Biometrics.FingerMatching
      - Devices.FingerScanners